---



- name: Create OpenShift Objects for 3scale multitenant
  k8s:
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
  - ./templates/3scale_project.j2
  - ./templates/operatorgroup.j2
  - ./templates/subscription.j2

- name: "Create threescale-registry-auth image pull secret in {{ API_MANAGER_NS }}"
  shell: |
    oc create secret docker-registry threescale-registry-auth \
        --docker-server=registry.redhat.io \
        --docker-username='{{ rht_service_token_user }}' \
        --docker-password={{ rht_service_token_password }} \
        -n  {{ API_MANAGER_NS }}


- name: Deploy 3scale API Manager for OpenBanking
  k8s:
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
  - ./templates/smtp.j2
  - ./templates/system-storage.j2
  - ./templates/apimanager.j2

# DC gets created after a few seconds. Pause for a bit.
- pause:
    minutes: 1

# The last Deployment run is apicast-production. So wait until it starts to ensure all pods are s
# tarted.
- name: Wait until apicast-production is running
  command: >
    oc rollout status dc/apicast-production --watch=true -n "{{ API_MANAGER_NS }}"

# Routes are created after some delay. Wait here for routes to  be ready.
- pause:
    minutes: 1


- name: workload Tasks Complete
  debug:
    msg: workload Tasks Complete
