---
# Implement your Post Workload deployment tasks here
- name: output workshop info
  agnosticd_user_info:
    msg: "{{ item }}"
  loop:
    - ""
    - "IOT Managed - {{ ocp4_workload_iot_managed_lab_title }} provisioned for {{ ocp_username }}"
    - ""
    - "To access lab content, login to the Solution Explorer (https://tutorial-web-app-webapp.{{ route_subdomain }}) and choose the "All Solution Patterns" tab."
    - ""
    - "Login using the username '{{ ocp4_workload_iot_managed_workshop_openshift_user_username }}', and password '{{ ocp4_workload_iot_managed_workshop_openshift_user_password }}'."
  when: not silent|bool

# Leave this as the last task in the playbook.
- name: post_workload tasks complete
  debug:
    msg: "Post-Workload Tasks completed successfully."
  when: not silent|bool
