---
# Implement your Post Workload deployment tasks here
- name: output workshop info
  debug:
    msg:
    - "user.info: "
    - "user.info: Change Data Capture with Debezium"
    - "user.info: "
    - "user.info: Solution Explorer (Start Here): "
    - "user.info: https://tutorial-web-app-webapp.{{ route_subdomain }}"
    - "user.info: "
    - "user.info: OpenShift Console: {{ console_url }}"
    - "user.info: Cluster admin login with '{{ ocp_username }}' / 'r3dh4t1!'"
  when: not silent|bool

# Leave this as the last task in the playbook.
- name: post_workload tasks complete
  debug:
    msg: "Post-Workload Tasks completed successfully."
  when: not silent|bool
