---
# Implement your Pre Workload deployment tasks here

- name: Ensuring AWS region is defined
  fail:
    msg: "This workload requires aws_region to be defined. Exiting..."
  when: (aws_region is not defined) and (ocp_workload_test is undefined)

- name: usercount debug
  debug:
    msg: "Debugging num_users {{ num_users }}"

- name: create usernames
  set_fact:
    users: "{{ users | default([]) + ['user'+item | string] }}"
  loop: "{{ range(1,((num_users | int) + 1)) | list }}"

# Figure out paths
- name: Get openshift hostname
  k8s_info:
    kind: Route
    name: console
    namespace: openshift-console
    api_version: route.openshift.io/v1
  register: openshift_console_route

- name: Set openshift host
  set_fact:
    route_subdomain: "{{ openshift_console_route.resources[0].status.ingress[0].routerCanonicalHostname }}"

- name: Set openshift console
  set_fact:
    console_url: "https://{{ openshift_console_route.resources[0].status.ingress[0].host }}"

- name: set bastion_fqdn
  set_fact:
    bastion_fqdn: "{{ subdomain_base }}"
  when: ocp_workload_test is undefined

- name: debug values
  debug:
    msg:
    - "console URL: {{ console_url }}"
    - "route subdomain: {{ route_subdomain }}"
    - "ocp_username: {{ ocp_username }}"

- name: debug bastion_host
  debug:
    msg:
    - "bastion host: {{ bastion_fqdn }}"
  when: bastion_fqdn is defined

# Leave this as the last task in the playbook.
- name: pre_workload tasks complete
  debug:
    msg: "Pre-Workload tasks completed successfully."
  when: not silent|bool
