---

# Implement your Post Workload deployment tasks here
# Implement your Post Workload deployment tasks here
- name: output workshop info
  debug:
    msg: "{{ item }}"
  loop:	
    - "user.info: "
    - "user.info: 3scale Multitenant API Manager - details"
    - "user.info: "
    - "user.info: OpenShift Console: https://console-openshift-console.{{ ocp_apps_domain }}"
    - "user.info: "
    - "user.info: 3scale MASTER Console : https://master.amp.{{ ocp_apps_domain }}"
    - "user.info: Master login with credentials master / {{ master_password }} "
    - "user.info: "
    - "user.info: 3scale MASTER API Host : {{ master_api_host }}"
    - "user.info: "
    - "user.info: 3scale MASTER Create Tenant URL : {{ create_tenant_url }}"
    - "user.info: "
  when: not silent|bool

# Leave this as the last task in the playbook.
- name: post_workload tasks complete
  debug:
    msg: "Post-Workload Tasks completed successfully."
  when: not silent|bool
