---
- name: virtualenv path to use for pip
  set_fact:
    pip_path: "{{ ansible_python_interpreter | dirname }}"

- name: "Uninstall lxml module from python"
  command: "{{ pip_path }}/pip uninstall lxml -y"
  become: True

- name: Remove all projects created for this workload
  k8s:
    state: absent
    api_version: project.openshift.io/v1
    kind: Project
    name: "{{ item }}"
  loop:
  - "{{ api_manager_namespace }}"


- name: post_workload Tasks Complete
  debug:
    msg: "Post-Software checks completed successfully - Removed"
