---
# Implement your Workload deployment tasks here


# Leave this as the last task in the playbook.
- name: Remove workload tasks complete
  debug:
    msg: "Remove Workload Tasks completed successfully."
  when: not silent|bool
