---
become_override: False
ocp_username: opentlc-mgr
silent: False


OCP_AMP_ADMIN_ID: api0

RESUME_CONTROL_PLANE_GWS: true


# Wildard DNS of OCP cluster environment
#ocp_apps_domain: "apps-{{ subdomain_base }}"          # Ravello environment
ocp_apps_domain: "apps.{{ subdomain_base }}"           # All other OCP environments


lab_name: 3scale-mt
API_MANAGER_NS: "{{lab_name}}-{{OCP_AMP_ADMIN_ID}}"
API_MANAGER_NAME: "{{lab_name}}-{{OCP_AMP_ADMIN_ID}}"
API_MANAGER_NS_DISPLAY: "3scale Multitenant API Manager"

threescale_operator_package_name: "3scale-operator"
threescale_currentCSV: "3scale-operator.v0.5.0"


# Output and log files to be added to invokers home directory
new_app_output_dir: "{{ lookup('env','HOME') }}/provisioning_output/{{subdomain_base}}"
new_app_output: "{{new_app_output_dir}}/{{API_MANAGER_NS}}-out.log"

# Red Hat Service Token for access to registry.redhat.io

rht_service_token_user: "change me"
rht_service_token_password: "change me"

# smtp
smtp_host: "smtp.sendgrid.net"
smtp_port: 587
smtp_authentication: plain
smtp_userid: changeme
smtp_passwd: changeme
smtp_domain: "redhat.com"

# CMS
use_rwo_for_cms: false

# RWO Storage size
_system_storage_size: 1Gi

adminEmailUser: "changeme"
adminEmailDomain: "changeme.com"

# S3 Credentials
#
AWS_ACCESS_KEY_ID: "change_me"
AWS_SECRET_ACCESS_KEY: "change_me"
AWS_BUCKET: 3scale-storage
AWS_HOSTNAME: s3.noobaa.svc:443
AWS_PROTOCOL: https
AWS_REGION: noobaa


###################################
