---
become_override: False
ocp_username: opentlc-mgr
silent: False


OCP_AMP_ADMIN_ID: api0

RESUME_CONTROL_PLANE_GWS: true


# Wildard DNS of OCP cluster environment
#ocp_apps_domain: "apps-{{ subdomain_base }}"          # Ravello environment
ocp_apps_domain: "apps.{{ subdomain_base }}"           # All other OCP environments


lab_name: 3scale-mt
api_manager_namespace: "{{lab_name}}-{{OCP_AMP_ADMIN_ID}}"
api_manager_name: "{{lab_name}}-{{OCP_AMP_ADMIN_ID}}"
api_manager_namespace_display: "3scale Multitenant API Manager"

threescale_operator_package_name: "3scale-operator"
threescale_currentCSV: "3scale-operator.v0.5.0"



# Red Hat Service Token for access to registry.redhat.io

rht_service_token_user: "change me"
rht_service_token_password: "change me"

# smtp
smtp_host: "smtp.sendgrid.net"
smtp_port: 587
smtp_authentication: plain
smtp_userid: changeme
smtp_passwd: changeme
smtp_domain: "redhat.com"

# CMS
use_rwo_for_cms: false

# RWO Storage size
_system_storage_size: 1Gi

adminEmailUser: "3scaleadmin"
adminEmailDomain: "redhat.com"

# S3 Credentials
#
AWS_ACCESS_KEY_ID: "change_me"
AWS_SECRET_ACCESS_KEY: "change_me"
AWS_BUCKET: 3scale-storage
AWS_HOSTNAME: s3.noobaa.svc:443
AWS_PROTOCOL: https
AWS_REGION: noobaa


###################################


# Minio instance
# Minio is used to replace the S3 API that is used by RHMI/Integreatly under
# normal circumstances.
minio_namespace: minio
minio_credential_secret: minio-credentials
minio_service_name: minio-service
minio_route_name: minio
minio_access_key: sandbox-minio-access
minio_secret_key: sandbox-minio-secret
minio_bucket_name: threescale
minio_bucket_region: us-east-1
minio_pvc_size: 1Gi
# 3scale API Manager Storage docker_secret
3scale_object_storage_secret_ref: aws-auth